name: dependencies_cleaner
description: A depencencies cleaner pre-commit hook.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  yaml: ^3.1.1
  path: ^1.8.1
  pre_commit_helpers:
    git:
      url: https://github.com/ReliableCauliflower/pre_commit_helpers